mainapp/urls.py
from django.urls import path

from .views import (
    BaseView,
    ProductDetailView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQuantityView,
    CheckoutView,
    MakeOrderView
)

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='details_products'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-quantity/<str:ct_model>/<str:slug>/', ChangeQuantityView.as_view(), name='change_quantity'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse
from django.utils import timezone



User = get_user_model()


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class MinResolutionErrorException(Exception):
    pass

class MaxResolutionErrorException(Exception):
    pass


class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respects_to = kwargs.get('with_respects_to')

        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.order_by('-id').all()[:5]
            products.extend(model_products)
        if with_respects_to:
            ct_model= ContentType.objects.filter(model=with_respects_to)
            if ct_model.exists():
                if with_respects_to in args:
                    return  sorted(products, key=lambda x: x.__class__.meta.model_name.startswith(with_respects_to), reverse=True )
        return products




class LatestProducts:

    objects = LatestProductsManager()

class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Ноутбуки': 'notebook__count',
        'Смартфоны': 'smartphone__count'
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        models = get_models_for_count('notebook', 'smartphone')
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data


class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):

    min_resolution = (400, 400)
    max_resolution = (2000, 2000)
    max_image_size = 3145728

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Имя продукта')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.title

    def get_model_name(self):
        return self.__class__.__name__.lower()

class Notebook(Product):

    diagonal = models.CharField(max_length=255, verbose_name='Диагональ')
    display = models.CharField(max_length=255, verbose_name='Тип дисплея')
    processor_freq = models.CharField(max_length=255, verbose_name='Частота процессора')
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    video = models.CharField(max_length=255, verbose_name='Видеокарта')
    time_without_charge = models.CharField(max_length=255, verbose_name='Время работы аккумулятора')


    def __str__(self):
        return f'{self.category.name} : {self.title}'

    def get_absolute_url(self):
        return get_product_url(self, 'details_products')




class Smartphone(Product):

    diagonal = models.CharField(max_length=255, verbose_name='Диагональ')
    display = models.CharField(max_length=255, verbose_name='Тип дисплея')
    resolution = models.CharField(max_length=255, verbose_name='Разрешение экрана')
    acc_volume = models.CharField(max_length=255, verbose_name='Батарея')
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    sd = models.BooleanField(default=True, verbose_name='Наличие SD карты')
    sd_volume = models.CharField(max_length=255, null=True, blank=True,  verbose_name='Обьем sd памяти')
    camera = models.CharField(max_length=255, verbose_name='Камера')
    front_camera = models.CharField(max_length=255, verbose_name='Фронтальная камера')


    def __str__(self):
        return f'{self.category.name} : {self.title}'

    def get_absolute_url(self):
        return get_product_url(self, 'details_products')


class CartProduct(models.Model):

    user = models.ForeignKey('Customer', verbose_name='Пользователь', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    quantity = models.PositiveIntegerField(default=1)
    total_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая Цена')

    def __str__(self):
        return 'Cart product: {}'.format(self.content_object.title)

    def save(self, *args, **kwargs):
        self.total_price = self.quantity * self.content_object.price
        super().save(*args, **kwargs)


class Cart(models.Model):

    owner = models.ForeignKey('Customer', null=True, verbose_name='Пользователь', on_delete=models.CASCADE)
    product = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    total_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая Цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)






class Customer(models.Model):

    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Заказы покупателя', related_name='related_customer')

    def __str__(self):
        return f'Customer: {self.user.first_name}, {self.user.last_name}'


class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'myself'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ завершен')
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель', related_name='related_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(max_length=255, verbose_name='Статус заказа', choices=STATUS_CHOICES, default=STATUS_NEW)
    buying_type = models.CharField(
        max_length=255,
        verbose_name='Тип покупки',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_DELIVERY
    )
    comment = models.TextField(verbose_name='Комментарий', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')
    order_date = models.DateField(verbose_name='Дата получения заказа', default=timezone.now)

    def __str__(self):
        return str(self.id)

mainapp/forms.py
from django import forms

from .models import Order


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = 'Дата получения заказа'


    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name',
            'last_name',
            'phone_number',
            'address',
            'buying_type',
            'order_date',
            'comment'
        )

mainapp/views.py
from django.db import transaction
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import DetailView, View
from .models import Notebook, Smartphone, Category, LatestProducts, Customer, Cart, CartProduct
from .mixins import CategoryDetailMixin, CartMixin
from .forms import OrderForm
from .utils import recalc_cart

class BaseView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        products = LatestProducts.objects.get_products_for_main_page('notebook', 'smartphone')
        context = {
            'categories': categories,
            'products': products,
            'cart': self.cart
        }
        return render(request, 'base.html', context)


class ProductDetailView(CartMixin, CategoryDetailMixin, DetailView):

    ct_model_model_class = {
        'notebook': Notebook,
        'smartphone': Smartphone,
    }

    def dispatch(self, request, *args, **kwargs):

        self.model = self.ct_model_model_class[kwargs['ct_model']]
        self.queryset = self.model._base_manager.all()
        return super().dispatch(request, *args, **kwargs)

    context_object_name = 'product'
    template_name = 'details_products.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ct_model'] = self.model._meta.model_name
        context['cart'] = self.cart
        return context


class CategoryDetailView(CartMixin, CategoryDetailMixin, DetailView):

    model = Category
    queryset = Category.objects.all()
    context_object_name = 'category'
    template_name = 'category_detail.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = self.cart
        return context

class AddToCartView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        products = content_type.model_class().objects.get(slug=product_slug)
        cart_products, created = CartProduct.objects.get_or_create(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=products.id
        )
        if created:
            self.cart.product.add(cart_products)
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, 'Товар успешно добавлен')
        return HttpResponseRedirect('/cart/')


class DeleteFromCartView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        products = content_type.model_class().objects.get(slug=product_slug)
        cart_products = CartProduct.objects.get(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=products.id
        )
        self.cart.product.remove(cart_products)
        recalc_cart(self.cart)
        cart_products.delete()
        messages.add_message(request, messages.INFO, 'Товар успешно удален')
        return HttpResponseRedirect('/cart/')


class ChangeQuantityView(CartMixin, View):

    def post(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        products = content_type.model_class().objects.get(slug=product_slug)
        cart_products = CartProduct.objects.get(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=products.id
        )
        qty = int(request.POST.get('qty'))
        cart_products.quantity = qty
        cart_products.save()
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, 'Количество изменено')
        return HttpResponseRedirect('/cart/')


class CartView(CartMixin, View):

    def get(self, request, *args, **kwargs):

        categories = Category.objects.get_categories_for_left_sidebar()
        context = {
            'cart': self.cart,
            'categories': categories
        }
        return render(request, 'cart.html', context)


class CheckoutView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        form = OrderForm(request.POST or None)
        context = {
            'cart': self.cart,
            'categories': categories,
            'form': form
        }
        return render(request, 'checkout.html', context)


class MakeOrderView(CartMixin, View):

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = OrderForm(request.POST or None)
        customer = Customer.objects.get(user=request.user)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.customer = customer
            new_order.first_name = form.cleaned_data['first_name']
            new_order.last_name = form.cleaned_data['last_name']
            new_order.phone_number = form.cleaned_data['phone_number']
            new_order.address = form.cleaned_data['address']
            new_order.buying_type = form.cleaned_data['buying_type']
            new_order.order_date = form.cleaned_data['order_date']
            new_order.comment = form.cleaned_data['comment']
            new_order.save()
            self.cart.in_order = True
            self.cart.save()
            new_order.cart = self.cart
            new_order.save()
            customer.orders.add(new_order)
            messages.add_message(request, messages.INFO, 'Спасибо за заказ! Менеджер с вами свяжется')
            return HttpResponseRedirect('/')
        return HttpResponseRedirect('/checkout/')

mainapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
(function($) {
    $('#id_sd').on('click', function(){
        if($('#id_sd').prop('checked') == true){
            $('#id_sd_volume').prop('readonly', false)
            $('#id_sd_volume').val('')
            $('#id_sd_volume').css('background', 'white')
        }else{
            $('#id_sd_volume').prop('readonly', true)
            $('#id_sd_volume').val('')
            $('#id_sd_volume').css('background', 'lightgray')
        }
    })
})(django.jQuery);
</script>
{% endblock %}

mainapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Shop Homepage - Start Bootstrap Template</title>


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">


</head>

<body>
  <style>
    body{
      padding-top: 56px;
    }
  </style>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'base' %}">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart' %}">Корзина <span class="badge badge-pill badge-warning">{{cart.product.count}}</span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Shop Name</h1>
        <div class="list-group">
          {% for category in categories %}
          <a href="{{ category.url }}" class="list-group-item">{{ category.name }}({{ category.count }})</a>
          {% endfor %}
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">
        {% block content %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
          {% endfor %}
        {% endif %}

        <h3 class="text-center mt-5 mb-5">Товары</h3>
        <div class="row">
          {% for product in products %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <h5>{{ product.price }}</h5>
                <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
                  <button class="btn btn-warning">Добавить в корзину</button>
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <!-- /.row -->
        {% endblock content %}
      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/cart.html
{% extends 'base.html' %}


{% block content %}
<h3 class="text-center mt-5 mb-5">Корзина {% if not cart.product.count %}Пусто{% endif %}</h3>

{% if cart.product.count %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Количество</th>
      <th scope="col">Общая цена</th>
      <th scope="col">Удаление</th>
    </tr>
  </thead>
  <tbody>
  {% for item in cart.product.all %}
    <tr>
      <th scope="row">{{ item.content_object.title }}</th>
      <td class="w-25"><img class="image-fluid w-100 h-10" src="{{ item.content_object.image.url }}"></td>
      <td>{{ item.content_object.price }} грн.</td>
      <td>
        <form action="{% url 'change_quantity' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}" method="post">
          {% csrf_token %}
          <input type="number" class="form-control" name="qty" min="1" value="{{ item.quantity }}">
          <br>
          <input type="submit" class="btn btn-dark" value="Изменить кол-во">
        </form>
      </td>
      <td>{{ item.total_price }} грн.</td>

      <td>
        <a href="{% url 'delete_from_cart' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}"><button class="btn btn-warning">Удалить из корзины</button></a>
      </td>
    </tr>
  {% endfor %}
  <tr>
    <td colspan="2"></td>
    <td>Итого:</td>
    <td>{{ cart.total_products }}</td>
    <td>{{ cart.total_price }} грн.</td>
    <td><a href="{% url 'checkout' %}"><button class="btn btn-primary">Перейти к оформлению</button> </a></td>
  </tr>
  </tbody>
</table>
{% endif %}
{% endblock content %}

mainapp/templates/category_detail.html
{% extends 'base.html' %}


{% block content %}

 <nav aria-label="breadcrumb" class="pt-3">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
    <li class="breadcrumb-item active">{{ category.name }}</li>

  </ol>
    </nav>

 <div class="row">
          {% for product in category_products %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <h5>{{ product.price }}</h5>
                  <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
                  <button class="btn btn-warning">Добавить в корзину</button>
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>

{% endblock content %}

mainapp/templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3 class="text-center mt-5 mb-5">Оформление заказа</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Количество</th>
      <th scope="col">Общая цена</th>
    </tr>
  </thead>
  <tbody>
  {% for item in cart.product.all %}
    <tr>
      <th scope="row">{{ item.content_object.title }}</th>
      <td class="w-25"><img class="image-fluid w-100 h-10" src="{{ item.content_object.image.url }}"></td>
      <td>{{ item.content_object.price }} грн.</td>
        <td>{{ item.quantity }}</td>
      <td>{{ item.total_price }} грн.</td>
    </tr>
  {% endfor %}
  <tr>
    <td colspan="2"></td>
    <td>Итого:</td>
    <td>{{ cart.total_products }}</td>
    <td>{{ cart.total_price }} грн.</td>
  </tr>
  </tbody>
</table>
<hr>
<h3 class="text-center mt-5 mb-5">Форма заказа</h3>
<form action="{% url 'make_order' %}" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" class="btn btn-success btn-block mb-3" value="Оформить заказ">
</form>

{% endblock content %}

mainapp/templates/details_products.html
{% extends 'base.html' %}
{% load specifications %}
{% block content %}
 <nav aria-label="breadcrumb" class="pt-3">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
    <li class="breadcrumb-item"><a href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
  </ol>
    </nav>
<div class="row">

    <div class="col-md-4">
        <img src="{{ product.image.url }}" class="image.fluid" style="width: 300px; height: 300px;">
    </div>
    <div class="col-md-8">
        <h3>
            {{ product.title }}
        </h3>
        <p>Цена: {{ product.price }} грн.</p>
        <p>Описание: {{ product.description }}</p>
        <hr>
        <a href="{% url 'add_to_cart' ct_model=ct_model slug=product.slug %} "><button class="btn btn-warning">Добавить в корзину</button></a>
    </div>
    <div>
        <p class="mt-4">Характеристики: </p>

        {{ product | product_spec }}

    </div>
</div>


{% endblock content %}

mainapp/templates/notebook_specification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table class="table">
  <tbody>
    <tr>
      <td>Диагональ</td>
      <td>{{ product.diagonal }}</td>
    </tr>
  <tr>
      <td>Тип дисплея</td>
      <td>{{ product.display }}</td>
    </tr>
  <tr>
      <td>Частота процессора</td>
      <td>{{ product.processor_freq }}</td>
    </tr>
  <tr>
      <td>Оперативаня память</td>
      <td>{{ product.ram }}</td>
    </tr>
  <tr>
      <td>Видеокарта</td>
      <td>{{ product.video }}</td>
    </tr>
  <tr>
      <td>Время работы аккумулятора</td>
      <td>{{ product.time_without_charge }}</td>
    </tr>
  </tbody>
</table>
</body>
</html>

mainapp/templates/smartphone_specification.html
<table class="table">
  <tbody>
    <tr>
      <td>Диагональ</td>
      <td>{{ product.diagonal }}</td>
    </tr>
  <tr>
      <td>Тип дисплея</td>
      <td>{{ product.display }}</td>
    </tr>
  <tr>
      <td>Разрешение экрана</td>
      <td>{{ product.resolution }}</td>
    </tr>
  <tr>
      <td>Батарея</td>
      <td>{{ product.acc_volume }}</td>
    </tr>
  <tr>
      <td>Оперативная память</td>
      <td>{{ product.ram}}</td>
    </tr>
  <tr>
      <td>Наличие слота для карты памяти</td>
      <td>{{ product.sd }}</td>
    </tr>
  <tr>
      <td>Обьем встроенной памяти</td>
      <td>{{ product.sd_volume }}</td>
    </tr>
  <tr>
      <td>Камера</td>
      <td>{{ product.camera }}</td>
    </tr>
  <tr>
      <td>Фронтальная камера</td>
      <td>{{ product.front_camera }}</td>
    </tr>
  </tbody>
</table>